### ISSUE TITLE
Allow consumers to toggle the return value of notify

### ISSUE THREAD

**Issue by nnichols** [SplashFinancial/clj-bugsnag#5]
# Feature Request

## Problem Statement

When the `notify` function is called, it, by default, returns the value of the post request made to bugsnag. This is counterintuitive to consumers since most logging interfaces in Clojure return nil.

## Ideal Solution

Allow the options map passed to `clj-bugsnag.core/notify` to toggle this behavior.

### Alternative solutions

A second function which returns nil

**Comment by brettrowberry** [comment]
We actually had a bug caused by this in one of our apps. Appreciate this change!

**Comment by nnichols** [comment]
Closed with: https://github.com/SplashFinancial/clj-bugsnag/pull/6
